### ISSUE TITLE
message received on backend is doubled 

### ISSUE THREAD

**Issue by getlose** [jawainc/simplecontact#27]
I've tried this plugin and this is what I need on my project. But the message that I got on the backend is doubled. 
also, the auto response mail is sent twice and it comes to spam folder of the recipient's address.
any solution for this? thanks

**Comment by jawainc** [comment]
I have double check it with clean install, i dont get any duplicate issue. Does any other plugin giving duplicate issues?

Are you using smtp for mail ?

**Comment by getlose** [comment]
These are all plugins that I am used on my project
> October Demo	1.0.1	Alexey Bobkov, Samuel Georges
Blog         1.2.14     Alexey Bobkov, Samuel Georges
User		1.3.3     Alexey Bobkov, Samuel Georges
Forum	1.1.1	    Alexey Bobkov, Samuel Georges
Builder	1.0.11  Alexey Bobkov, Samuel Georges
reportfx	1.0.18   Nanda Satria(my own plugin using builder)
Backend Plus	1.5.7	Gergő Szabó
IdeHelper	  1.0.5	Flynsarmy
Code login	1.0.4	Vojta Svoboda
Simple Contact  1.1.1	Jawad

Yes I am using smtp for mail.
Any Idea why this duplicate message happening?

**Comment by mkhalil-git** [comment]
check the script in your layout maybe u  duplicate  {% framework %}

i had experience with this issue here the issue [#2379](https://github.com/octobercms/october/issues/2379)

**Comment by getlose** [comment]
@MK4Tech yeaaah thank you! I deleted the first {% framework %} and it is not doubled again.  So it is not affect any other plugin? I mean are other plugins can works fine on only one {% framework extras %} ?
