### ISSUE TITLE
Error after upgrade. (Translate installed)

### ISSUE THREAD

**Issue by sigfriedseldeslachts** [jawainc/simplecontact#33]
Hey Jawainc,

I got this error message after upgrading, And thanks to this I had to reinstall my whole octobercms because I got this error on every page. Also translate is installed. Looks like this is the same as issue #21 but I didn't have this before upgrading. Weird

"SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at' (SQL: create table `zainab_simplecontact_contact` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) null, `email` varchar(255) null, `phone` varchar(255) null, `subject` varchar(255) null, `message` text null, `is_new` tinyint(1) not null default '1', `created_at` timestamp not null default '0000-00-00', `updated_at` timestamp not null default '0000-00-00') default character set utf8 collate utf8_unicode_ci engine = InnoDB)"

Greetings
Me

**Comment by jawainc** [comment]
sorry for the inconvienence 
https://github.com/laravel/framework/issues/3602
check this issue

**Comment by sigfriedseldeslachts** [comment]
No problem.
It now works after a few reinstalls, but I have no clue about it fixed itself.

**Comment by vojtasvoboda** [comment]
Fixed by #35

**Comment by vojtasvoboda** [comment]
Should be now at market, @sigfriedseldeslachts can you test it please?

**Comment by sigfriedseldeslachts** [comment]
@vojtasvoboda I have updated without any issues.
