### ISSUE TITLE
Not installing and breaking "manage plugins" page

### ISSUE THREAD

**Issue by Osnapman** [jawainc/simplecontact#42]
**Expected behavior**

Install Simple Contact Us, build and use contact form on a page of the website.

**Actual behavior**

Does not show up as installed, breaks "manage plugins" page and gives this error https://puu.sh/tqS4G/32aaa37d35.png

**Reproduce steps**

Just installed Simple Contact Us on shared host, went to click the button "manage plugins" and the error showed up.

**October build**

382

**Other Information**
Had to go into Cpanel and go to plugins folder, then delete the simple contact folder for the page to work again

**Comment by jawainc** [comment]
Just did fresh install, it goes without any problems.
Did you 1st install Translate plugin?

Log into your cPanel , go to your web directory, then in your public_html(or www) -> plugins 
delete zainab folder

**Comment by Osnapman** [comment]
Got it working, I guess my Translate plugin was broken. Just reinstalled the translate plugin and it worked.
