### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by LucasZdv** [jawainc/simplecontact#45]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'stockist.zainab_simplecontact_contact' doesn't exist (SQL: select count(*) as aggregate from `zainab_simplecontact_contact` where `is_new` = 1)

http://nimb.ws/K5doDC

**Comment by jawainc** [comment]
Did you install Translate plugin?

**Comment by LucasZdv** [comment]
Thanks, I installed the RainLab.Translate manually and works but are not suppose what, this installs the dependencies?

     /**
     * @var array Plugin dependencies
     */
    public $require = ['RainLab.Translate'];

@daftspunk

**Comment by jawainc** [comment]
unfortunately not

**Comment by LucasZdv** [comment]
I create an issue in octobercms this worked before. https://github.com/octobercms/october/issues/2778
